baseURL = "/"
languageCode = "en"
title = "SolidResume Example"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "term", "section"]

[params]
siteDescription = "SolidResume â€” single-page CV example"
printVersion = true

[params.themes]
default = "auto"

[params.author]
image = "/img/pgibbons.jpg"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.nb]
    languageName = "Norsk"
    weight = 2

[module]
  # Explicitly import the parent theme/module
  [[module.imports]]
    path = "github.com/evensollid/SolidResume"

